FROM  adoptopenjdk:15.0.2_7-jre-openj9-0.24.0-focal
#FROM azul/zulu-openjdk-alpine:14
#FROM adoptopenjdk/openjdk15:latest

ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
		&& apt-get install -y --no-install-recommends dialog \
        && apt-get update \
	&& apt-get install -y --no-install-recommends openssh-server \
	&& echo "$SSH_PASSWD" | chpasswd

COPY sshd_config /etc/ssh/

COPY init.sh /usr/local/bin/  
RUN chmod u+x /usr/local/bin/init.sh

ENV SSH_PORT 2222
EXPOSE 2222

RUN mkdir /opt/app
COPY app.jar /opt/app/app.jar
RUN chmod 777 /opt/app/app.jar

EXPOSE 8080
RUN echo $(java -XshowSettings:vm)
CMD ["java", "-jar", "/opt/app/app.jar"]
ENTRYPOINT ["init.sh"]	
#RUN echo $(java -XshowSettings:vm)